# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import todo_pb2 as todo__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in todo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CMSStub(object):
    """The CMS gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.export_document = channel.unary_stream(
                '/cms.CMS/export_document',
                request_serializer=todo__pb2.ExportItemRequest.SerializeToString,
                response_deserializer=todo__pb2.ExportItemResponse.FromString,
                _registered_method=True)
        self.create_document = channel.unary_unary(
                '/cms.CMS/create_document',
                request_serializer=todo__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=todo__pb2.CreateItemResponse.FromString,
                _registered_method=True)


class CMSServicer(object):
    """The CMS gRPC service
    """

    def export_document(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_document(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CMSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'export_document': grpc.unary_stream_rpc_method_handler(
                    servicer.export_document,
                    request_deserializer=todo__pb2.ExportItemRequest.FromString,
                    response_serializer=todo__pb2.ExportItemResponse.SerializeToString,
            ),
            'create_document': grpc.unary_unary_rpc_method_handler(
                    servicer.create_document,
                    request_deserializer=todo__pb2.CreateItemRequest.FromString,
                    response_serializer=todo__pb2.CreateItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cms.CMS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cms.CMS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CMS(object):
    """The CMS gRPC service
    """

    @staticmethod
    def export_document(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cms.CMS/export_document',
            todo__pb2.ExportItemRequest.SerializeToString,
            todo__pb2.ExportItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_document(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cms.CMS/create_document',
            todo__pb2.CreateItemRequest.SerializeToString,
            todo__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
