# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x03\x63ms\"1\n\x11\x45xportItemRequest\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\"5\n\x12\x45xportItemResponse\x12\x1f\n\x08\x64ocument\x18\x01 \x03(\x0b\x32\r.cms.Document\"4\n\x11\x43reateItemRequest\x12\x1f\n\x08\x64ocument\x18\x01 \x01(\x0b\x32\r.cms.Document\"5\n\x12\x43reateItemResponse\x12\x1f\n\x08\x64ocument\x18\x01 \x01(\x0b\x32\r.cms.Document\"T\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t2\x8f\x01\n\x03\x43MS\x12\x44\n\x0f\x65xport_document\x12\x16.cms.ExportItemRequest\x1a\x17.cms.ExportItemResponse0\x01\x12\x42\n\x0f\x63reate_document\x12\x16.cms.CreateItemRequest\x1a\x17.cms.CreateItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPORTITEMREQUEST']._serialized_start=19
  _globals['_EXPORTITEMREQUEST']._serialized_end=68
  _globals['_EXPORTITEMRESPONSE']._serialized_start=70
  _globals['_EXPORTITEMRESPONSE']._serialized_end=123
  _globals['_CREATEITEMREQUEST']._serialized_start=125
  _globals['_CREATEITEMREQUEST']._serialized_end=177
  _globals['_CREATEITEMRESPONSE']._serialized_start=179
  _globals['_CREATEITEMRESPONSE']._serialized_end=232
  _globals['_DOCUMENT']._serialized_start=234
  _globals['_DOCUMENT']._serialized_end=318
  _globals['_CMS']._serialized_start=321
  _globals['_CMS']._serialized_end=464
# @@protoc_insertion_point(module_scope)
